### ISSUE TITLE
dfo = depth first order

### ISSUE THREAD

**Issue by cbaggers** [guicho271828/sbcl-wiki#1]
https://ccl.clozure.com/irc-logs/sbcl/sbcl-2018-01.txt

> 2018-01-24T12:48:50Z Baggers: what does DFO stand for. I'm assuming something like data flow order but its not in the TLA file
> 2018-01-24T13:16:24Z stassats: depth first order

Doesnt explain much of how it is used

**Comment by cbaggers** [comment]
`dfo-as-needed` calls `find-dfo` which:

> ;;; Find the DFO for a component, deleting any unreached blocks and
> ;;; merging any other components we reach. We repeatedly iterate over
> ;;; the entry points, since new ones may show up during the walk.

**Comment by cbaggers** [comment]
DFO sounds kind of similar to how 'The Python Compiler for CMU Common Lisp' defines 'Find components'

> Find the flow graph components and compute a depth-first ordering. Delete unreachable code. Seperate top-level code from run-time cdoe, and determine which componenets are top-level componenets.

**Comment by guicho271828** [comment]
thank you!

**Comment by guicho271828** [comment]
oh, sorry the wiki was configured incorrectly. It should be free to edit for everyone now

**Comment by cbaggers** [comment]
@guicho271828 Thanks :)
